### ISSUE TITLE
Regression: Configuration via environment variable

### ISSUE THREAD

**Issue by tlnd** [travelping/ping-exporter#2]
Configuration of targets via environment variable broke between 0.4.0 and 0.5.0:

```
$ docker run -ti --rm -e PINGEXPORTER_PING_TARGET=127.0.0.1  travelping/ping-exporter:0.4.0
INFO[0000] adding target for host 127.0.0.1 (127.0.0.1)  source="target.go:64"
INFO[0000] starting cgw exporter (Version: 0.4.0)        source="main.go:104"
INFO[0000] Listening for /metrics on :9427               source="main.go:122"

$ docker run -ti --rm -e PINGEXPORTER_PING_TARGET=127.0.0.1  travelping/ping-exporter:0.5.0
ERRO[0000] open /etc/ping-exporter/ping-exporter.yaml: no such file or directory  source="main.go:140"
```

**Comment by mgumz** [comment]
The issue is not the "environment variable does not work" but the "config file not there". The "regression" happened via 22f67d7187f8292a0acdf0fddbf8f1e0b436f620: Before, a "hard coded" config file named `ping-exporter.yaml` was assumed under a bunch of paths (`/etc/ping-exporter`, `.`) and eventually (silently) evaluated. That changed when I introduced the `-c` option which defaults to `/etc/ping-exporter/ping-exporter.yaml`.

We will see how to solve the issue (restore almost the old behaviour)
